name: Validate Jira Ticket in PR

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-jira:
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR title
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            core.setOutput("title", title);

      - name: Check Jira ticket format
        id: check_format
        run: |
          echo "PR Title: ${{ steps.get_pr.outputs.title }}"
          if [[ "${{ steps.get_pr.outputs.title }}" =~ ([A-Z]+-[0-9]+) ]]; then
            echo "✅ Found Jira ticket format"
            echo "ticket=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "❌ No valid Jira ticket (e.g. SCRUM-123) found in PR title"
            exit 1
          fi

      - name: Validate ticket exists in Jira
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
        run: |
          ticket="${{ steps.check_format.outputs.ticket }}"
          echo "🔎 Checking if Jira ticket $ticket exists..."

          response=$(curl -s -u $JIRA_EMAIL:$JIRA_API_TOKEN \
            -H "Accept: application/json" \
            "https://$JIRA_DOMAIN/rest/api/3/issue/$ticket")

          if echo "$response" | grep -q '"errorMessages"'; then
            echo "❌ Jira ticket not found: $ticket"
            exit 1
          else
            echo "✅ Jira ticket $ticket exists"
          fi
